const $=s=>document.querySelector(s);
const load=(k,d)=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d));
const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let products=load('products',[
{id:1,name:'Coocaa 32"',sku:'COO32',price:1450000,cost:1200000,stock:5,serial:'COO32-001'},
{id:2,name:'Samsung 43"',sku:'SAM43',price:3999000,cost:3300000,stock:3,serial:'SAM43-001'},
{id:3,name:'LG 50"',sku:'LG50',price:5999000,cost:4900000,stock:2,serial:'LG50-001'}
]);
let customers=load('customers',[]);
let sales=load('sales',[]);
let deliveries=load('deliveries',[]);
let page='home';

function rup(n){return new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n)}
function toast(t){let x=$('.toast');x.textContent=t;x.style.display='block';setTimeout(()=>x.style.display='none',1800)}
function login(){app.innerHTML=`<div class="login"><div class="card"><div class="brand"><div class="gold" style="font-size:14px;font-weight:800">DR ELEKTRONIK</div><b>TOKO TV JOGJA</b><p class="muted">Sistem Kasir & Manajemen Toko</p></div><div class="field"><label>Username</label><input id="u" value="admin"></div><div class="field"><label>Password</label><input id="p" type="password" value="1234"></div><button class="btn primary" style="width:100%" onclick="doLogin()">Masuk</button><p class="muted" style="text-align:center;font-size:12px">Demo: admin / 1234</p></div></div>`}
function doLogin(){if($('#u').value==='admin'&&$('#p').value==='1234'){sessionStorage.in=1;render()}else toast('Username/password salah')}
function render(){if(!sessionStorage.in)return login(); app.innerHTML=`<div class="app"><header class="top"><div class="toprow"><div><h1>TOKO TV JOGJA</h1><small>DR Elektronik</small></div><button class="btn" style="background:#222;color:#fff" onclick="logout()">Keluar</button></div></header><main class="content" id="main"></main><nav class="nav">${nav('home','⌂','Beranda')}${nav('products','▣','Produk')}${nav('sales','＋','Jual')}${nav('customers','♙','Pelanggan')}${nav('report','▤','Laporan')}</nav><div class="toast"></div></div>`;show()}
function nav(p,i,t){return `<button class="${page===p?'active':''}" onclick="page='${p}';show()"><div style="font-size:22px">${i}</div>${t}</button>`}
function show(){let m=$('#main');if(page==='home')home(m);if(page==='products')productPage(m);if(page==='sales')salesPage(m);if(page==='customers')customerPage(m);if(page==='report')reportPage(m)}
function home(m){let omzet=sales.reduce((a,s)=>a+s.total,0),profit=sales.reduce((a,s)=>a+s.profit,0),stock=products.reduce((a,p)=>a+p.stock,0);m.innerHTML=`<h2>Dashboard</h2><div class="stats"><div class="stat">Omzet<b>${rup(omzet)}</b></div><div class="stat">Laba<b>${rup(profit)}</b></div><div class="stat">Produk<b>${products.length}</b></div><div class="stat">Stok<b>${stock}</b></div></div><div class="section"><div class="sectionhead"><h2>Transaksi terbaru</h2><button class="btn goldbtn" onclick="page='sales';show()">Penjualan</button></div><div class="list">${sales.slice(-5).reverse().map(s=>`<div class="item"><div><b>${s.no}</b><span class="muted">${s.customer||'Umum'} · ${s.product}</span></div><strong>${rup(s.total)}</strong></div>`).join('')||'<div class="empty">Belum ada transaksi</div>'}</div></div><div class="section"><h2>Stok menipis</h2><div class="list">${products.filter(p=>p.stock<=2).map(p=>`<div class="item"><div><b>${p.name}</b><span class="muted">${p.sku}</span></div><span class="tag">${p.stock} unit</span></div>`).join('')||'<div class="empty">Stok aman</div>'}</div></div>`}
function productPage(m){m.innerHTML=`<div class="sectionhead"><h2>Produk & Stok</h2><button class="btn goldbtn" onclick="addProduct()">+ Produk</button></div><div class="list">${products.map(p=>`<div class="item"><div><b>${p.name}</b><span class="muted">${p.sku} · Modal ${rup(p.cost)}</span><div class="tag" style="margin-top:6px">SN ${p.serial}</div></div><div style="text-align:right"><strong>${rup(p.price)}</strong><div>${p.stock} stok</div></div></div>`).join('')}</div>`}
function addProduct(){let name=prompt('Nama produk');if(!name)return;let price=+prompt('Harga jual','1500000'),cost=+prompt('Harga modal','1200000'),stock=+prompt('Stok','1'),serial=prompt('Serial number','SN-001');products.push({id:Date.now(),name,sku:'SKU'+Date.now().toString().slice(-5),price,cost,stock,serial});save('products',products);toast('Produk ditambahkan');show()}
function salesPage(m){m.innerHTML=`<h2>Penjualan Baru</h2><div class="card" style="padding:18px"><div class="field"><label>Produk</label><select id="sp">${products.filter(p=>p.stock>0).map(p=>`<option value="${p.id}">${p.name} — ${rup(p.price)} (stok ${p.stock})</option>`).join('')}</select></div><div class="field"><label>Pelanggan</label><select id="sc"><option value="">Umum</option>${customers.map(c=>`<option>${c.name}</option>`).join('')}</select></div><div class="row"><div class="field"><label>Diskon</label><input id="disc" type="number" value="0"></div><div class="field"><label>Ongkir</label><input id="ship" type="number" value="0"></div></div><div class="row"><div class="field"><label>Pemasangan</label><input id="install" type="number" value="0"></div><div class="field"><label>Bonus</label><select id="bonus"><option>Bracket</option><option>Antena</option><option>Tanpa bonus</option></select></div></div><div class="field"><label>Pembayaran</label><select id="pay"><option>Cash</option><option>Transfer</option><option>QRIS</option></select></div><div class="section"><div class="total" id="stotal">Total</div></div><button class="btn primary" style="width:100%" onclick="sell()">Simpan Transaksi</button></div>`;['sp','disc','ship','install'].forEach(x=>$('#'+x)?.addEventListener('input',calc));calc()}
function calc(){let p=products.find(x=>x.id==$('#sp')?.value);if(!p)return;let total=p.price-(+$('#disc').value||0)+(+$('#ship').value||0)+(+$('#install').value||0);$('#stotal').textContent=rup(total)}
function sell(){let p=products.find(x=>x.id==$('#sp').value);if(!p||p.stock<1)return toast('Stok habis');let discount=+$('#disc').value||0,ship=+$('#ship').value||0,install=+$('#install').value||0,total=p.price-discount+ship+install;let no='TVJ-'+new Date().getFullYear()+'-'+String(sales.length+1).padStart(4,'0');let s={no,product:p.name,customer:$('#sc').value,total,profit:total-p.cost,bonus:$('#bonus').value,payment:$('#pay').value,date:new Date().toISOString(),serial:p.serial};sales.push(s);p.stock--;save('sales',sales);save('products',products);deliveries.push({no,customer:s.customer||'Umum',product:p.name,status:'Belum Dikirim'});save('deliveries',deliveries);alert(`Transaksi ${no}\n${p.name}\nTotal: ${rup(total)}\nSN: ${p.serial}`);toast('Transaksi tersimpan');page='home';render()}
function customerPage(m){m.innerHTML=`<div class="sectionhead"><h2>Pelanggan</h2><button class="btn goldbtn" onclick="addCustomer()">+ Pelanggan</button></div><div class="list">${customers.map(c=>`<div class="item"><div><b>${c.name}</b><span class="muted">${c.phone||'-'}</span></div><span>${sales.filter(s=>s.customer===c.name).length} transaksi</span></div>`).join('')||'<div class="empty">Belum ada pelanggan</div>'}</div><div class="section"><h2>Antar & Pasang</h2><div class="list">${deliveries.map(d=>`<div class="item"><div><b>${d.no}</b><span class="muted">${d.customer} · ${d.product}</span></div><span class="tag">${d.status}</span></div>`).join('')||'<div class="empty">Belum ada pengiriman</div>'}</div>`}
function addCustomer(){let name=prompt('Nama pelanggan');if(!name)return;let phone=prompt('No. WhatsApp');customers.push({name,phone});save('customers',customers);toast('Pelanggan ditambahkan');show()}
function reportPage(m){let omzet=sales.reduce((a,s)=>a+s.total,0),profit=sales.reduce((a,s)=>a+s.profit,0);m.innerHTML=`<h2>Laporan</h2><div class="stats"><div class="stat">Omzet<b>${rup(omzet)}</b></div><div class="stat">Laba<b>${rup(profit)}</b></div><div class="stat">Transaksi<b>${sales.length}</b></div><div class="stat">TV terjual<b>${sales.length}</b></div></div><div class="section"><h2>Semua transaksi</h2><div class="list">${sales.slice().reverse().map(s=>`<div class="item"><div><b>${s.no}</b><span class="muted">${s.product} · ${s.customer||'Umum'} · ${s.payment}</span></div><strong>${rup(s.total)}</strong></div>`).join('')||'<div class="empty">Belum ada transaksi</div>'}</div></div>`}
function logout(){sessionStorage.clear();render()}render();
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
